### ISSUE TITLE
Looks like tests could be broken

### ISSUE THREAD

**Issue by Acribbs** [cgat-developers/cgat-tests#1]
hi @AndreasHeger looking at the code in this repository (not sure how or where jenkins tests are now ran) it seems as though tests should be failing because they haven't reflected the new code layout. Could be wrong though.

**Comment by sebastian-luna-valero** [comment]
I think this issue is outdated. Please reopen if necessary.

**Comment by Acribbs** [comment]
Yes thanks, I fixed the pipeline testing and all tests running on my environment are passing with flying colours
